<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Authors>Jannik Buschke</Authors>
        <IncludeSymbols>true</IncludeSymbols>
        <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageId>TinyEventStore</PackageId>
        <RootNamespace>TinyEventStore</RootNamespace>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup>
        <Title>TinyEventStore</Title>
        <Description>TinyEventStore does the thing!</Description>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <Optimize>true</Optimize>
        <Tailcalls>true</Tailcalls>
    </PropertyGroup>

    <ItemGroup>

        <None Include="README.md" Pack="true" PackagePath="\"/>
        <Compile Include="Ids.fs"/>
        <Compile Include="Interfaces.fs"/>
        <Compile Include="Types.fs"/>
        <Compile Include="ApplyEvents.fs"/>
        <Compile Include="HandleCommandAndAppendEvents.fs"/>
        <!-- <Compile Include="PureTinyEventStore.fs" /> -->
        <Compile Include="Projections.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FsToolkit.ErrorHandling" Version="4.*"/>
        <PackageReference Include="FsToolkit.ErrorHandling.TaskResult" Version="4.*"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.*"/>
        <PackageReference Include="FSharp.SystemTextJson" Version="*"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.*"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.*">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

<!--
    <Import Project="..\..\.paket\Paket.Restore.targets"/>
-->
</Project>
